version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13.3
    steps:
      - run: |
          mkdir -p ~/bin
          echo 'export PATH="$HOME/bin:$PATH"' >> $BASH_ENV
      - checkout
      - run: make ci-setup-linux-amd64
      - run: make check
      - run: bash <(curl -s https://codecov.io/bash)
      - run: make dist
      - run: |
          if [ "$CIRCLE_TAG" ]; then
            make release
          fi

workflows:
  version: 2
  all:
    jobs:
      - build:
          context: open-source
          filters:
            tags:
              only: /.*/
